In [2]:
import pandas as pd
a=pd.read_csv('/train.csv')
print(a)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [12]:
x=a.drop(columns=['price_range'])

In [13]:
print(x)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0

In [14]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
xtrain=scaler.fit_transform(x)

In [16]:
print(xtrain)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]


In [17]:
from sklearn.model_selection import train_test_split

In [18]:
b=train_test_split(xtrain)

In [21]:
print(b)

[array([[0.20908484, 1.        , 0.24      , ..., 1.        , 0.        ,
        0.        ],
       [0.35671343, 0.        , 0.04      , ..., 1.        , 1.        ,
        0.        ],
       [0.14094856, 1.        , 0.44      , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.2745491 , 0.        , 0.08      , ..., 0.        , 1.        ,
        1.        ],
       [0.84235137, 1.        , 0.88      , ..., 1.        , 1.        ,
        1.        ],
       [0.26252505, 0.        , 0.16      , ..., 1.        , 0.        ,
        1.        ]]), array([[0.29726119, 0.        , 0.48      , ..., 1.        , 1.        ,
        1.        ],
       [0.65998664, 0.        , 0.76      , ..., 0.        , 0.        ,
        0.        ],
       [0.00133601, 1.        , 0.52      , ..., 1.        , 0.        ,
        1.        ],
       ...,
       [0.19171677, 0.        , 0.8       , ..., 1.        , 1.        ,
        1.        ],
       [0.59853039, 0.        , 0

In [28]:
import pandas as pd
k=pd.read_csv('/heart.csv')
print(k)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [29]:
u=k.drop(columns=['target'])
print(u)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0    

In [30]:
v=k['target']
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
utrain=scaler.fit_transform(u)


In [32]:
print(utrain)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


In [34]:
b1=train_test_split(utrain)
print(b1)

[array([[0.54166667, 0.        , 0.        , ..., 0.5       , 0.25      ,
        1.        ],
       [0.5625    , 1.        , 0.        , ..., 0.5       , 0.25      ,
        0.33333333],
       [0.45833333, 1.        , 0.        , ..., 0.5       , 0.75      ,
        1.        ],
       ...,
       [0.33333333, 1.        , 0.        , ..., 0.5       , 0.75      ,
        1.        ],
       [0.39583333, 1.        , 0.        , ..., 1.        , 0.        ,
        0.66666667],
       [0.52083333, 1.        , 0.66666667, ..., 0.5       , 0.        ,
        1.        ]]), array([[0.25      , 1.        , 0.33333333, 0.24528302, 0.07077626,
        0.        , 0.5       , 0.84732824, 0.        , 0.        ,
        1.        , 0.        , 0.66666667],
       [0.58333333, 0.        , 0.        , 0.32075472, 0.40410959,
        0.        , 0.        , 0.67175573, 0.        , 0.        ,
        1.        , 0.25      , 0.66666667],
       [0.58333333, 1.        , 0.33333333, 0.28301887, 0.3

In [36]:
import numpy as np
x1=utrain[0]
x2=utrain[1]
x3=utrain[2]
x4=utrain[3]
x5=utrain[4]
x6=utrain[5]
x7=utrain[6]
x8=utrain[7]
x9=utrain[8]
x10=utrain[9]
x11=utrain[10]
x12=utrain[11]
x13=utrain[12]
y_p=[]
def perceptron(w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,b):
  for i in range(len(x1)):
    z=x1[i]*w1+x2[i]*w2+x3[i]*w3+x4[i]*w4+x5[i]*w5+x6[i]*w6+x7[i]*w7+x8[i]*w8+x9[i]*w9+x10[i]*w10+x11[i]*w11+x12[i]*w12+x12[i]*w12+x13[i]*w13+b
    s=1/1+np.exp(-z)
    if(s>=0.5):
      y_p.append(1)
    else:
      y_p.append(0)

In [37]:
perceptron(1,1,1,1,1,1,1,1,1,1,1,1,1,1)

In [38]:
print(y_p)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
